Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'test/dummy/bin/setup'
    - 'test/dummy/bin/update'
